
services:

  llama3.2:
    provider:
      type: model
      options:
        model: ai/llama3.2

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3

  qwen3:
    provider:
      type: model
      options:
        model: jimclark106/qwen3:4b-F16

  mcp-gateway:
    provider:
      type: mcp
      options:
        tools: brave_web_search,get_article,get_summary,get_related_topics,send-email
        name: research

  observability:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  research-agent:
    image: jimclark106/agent:latest
    depends_on:
      - llama3.2
      - qwen3
      - gemma
      - mcp-gateway
      - observability
    command:
      - |
        Use any of the available tools to research the topic
        "the Model Context Protocol (MCP) and its applications in AI agents"
        and when complete, send an email to slimslenderslacks@gmail.com with 
        the results and the subject "MCP Research Results".

