
services:

  llama3.2:
    provider:
      type: model
      options:
        model: ai/llama3.2

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3

  #agents:
    #image: demo/agents
    #ports:
      #- "7777:7777"
    #environment:
      #- OPENAI_API_KEY=$OPENAI_API_KEY
    #volumes:
      #- ./agents.yaml:/agents.yaml
    #depends_on:
      #- mcp-gateway
      #- llama3.2
      #- gemma

  #agents-ui:
    #image: demo/ui
    #ports:
      #- "3000:3000"
    #environment:
      #- AGENTS_URL=http://localhost:7777
    #depends_on:
      #- agents

  mcp-gateway:
    provider:
      type: mcp
      options:
        tools: brave_web_search,get_article,get_summary,get_related_topics,send-email
        name: research

  research-agent:
    image: jimclark106/agent:latest
    depends_on:
      - llama3.2
      - mcp-gateway
    command:
      - |
        Use any of the available tools to research the topic
        "the Model Context Protocol (MCP) and its applications in AI agents"
        and when complete, send an email to slimslenderslacks@gmail.com with 
        the results and the subject "MCP Research Results".

