
services:

  model-llama3.2-model:
    provider:
      type: model
      options:
        model: ai/llama3.2

  mcp-gateway:
    provider:
      type: mcp
      options:
        tools: brave_web_search,get_article,get_summary,get_related_topics,send-email

  research-agent:
    image: jimclark106/agent:latest
    depends_on:
      - model-llama3.2-model
      - mcp-gateway
    command:
      - |
        Use any of the available tools to research the topic
        "the Model Context Protocol (MCP) and its applications in AI agents"
        and when complete, send an email to slimslenderslacks@gmail.com with 
        the results and the subject "MCP Research Results".

